<?php

namespace App\Services;

use App\Models\Ticket;
use App\Models\TicketResponse;
use App\Models\AdminUser;
use App\Models\Customer;
use App\Models\User;
use App\Events\TicketStatusChanged;
use Illuminate\Support\Facades\Log;

use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Builder;

class TicketService
{
    /**
     * Create a new customer ticket with proper validation and business logic.
     *
     * @param Customer $customer
     * @param User $user
     * @param array $data
     * @return Ticket
     * @throws \InvalidArgumentException
     */
    public function createCustomerTicket(Customer $customer, User $user, array $data): Ticket
    {
        // Validate input parameters
        $this->validateCustomerTicketCreation($customer, $user, $data);

        // Validate and normalize input data
        $normalizedData = $this->normalizeTicketData($data);

        // Create ticket with normalized data (ticket number will be auto-generated by model)
        $ticket = Ticket::create([
            'customer_id' => $customer->id,
            'subject' => $normalizedData['subject'],
            'description' => $normalizedData['description'],
            'status' => Ticket::STATUS_OPEN,
            'priority' => $normalizedData['priority'],
            'category' => $normalizedData['category'],
            'source' => 'customer_portal',
        ]);

        // Create initial customer response
        $this->createInitialResponse($ticket, $user, $normalizedData['description']);

        // Log ticket creation
        $this->logTicketCreation($ticket, $customer, $user);

        return $ticket->load(['responses.user', 'responses.adminUser', 'assignedTo', 'department']);
    }

    /**
     * Validate customer ticket creation parameters.
     */
    protected function validateCustomerTicketCreation(Customer $customer, User $user, array $data): void
    {
        // Validate customer is active
        if (!$customer->status) {
            throw new \InvalidArgumentException('Cannot create tickets for inactive customers');
        }

        // Validate user belongs to customer
        if (!$user->isCustomer() || $user->userable_id !== $customer->id) {
            throw new \InvalidArgumentException('User does not belong to the specified customer');
        }

        // Validate required data fields
        $validator = validator($data, [
            'subject' => 'required|string|max:255|min:5',
            'description' => 'required|string|max:5000|min:10',
            'priority' => 'nullable|string|in:low,medium,high,urgent',
            'category' => 'nullable|string|max:100',
        ]);

        if ($validator->fails()) {
            throw new \InvalidArgumentException('Validation failed: ' . $validator->errors()->first());
        }
    }

    /**
     * Get paginated tickets for a customer with filters and eager loading.
     *
     * @param Customer $customer
     * @param array $filters
     * @param int $perPage
     * @return LengthAwarePaginator
     */
    public function getCustomerTickets(Customer $customer, array $filters = [], int $perPage = 10): LengthAwarePaginator
    {
        $query = $this->buildCustomerTicketsQuery($customer, $filters);

        // Limit per page to prevent abuse
        $perPage = min($perPage, 50);

        return $query->paginate($perPage);
    }

    /**
     * Get a specific customer ticket with authorization check.
     *
     * @param Customer $customer
     * @param int $ticketId
     * @return Ticket
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function getCustomerTicket(Customer $customer, int $ticketId): Ticket
    {
        return $customer->tickets()
            ->with([
                'responses.user',
                'responses.adminUser',
                'assignedTo',
                'department',
                'customer'
            ])
            ->findOrFail($ticketId);
    }

    /**
     * Get ticket responses.
     *
     * @param Ticket $ticket
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getTicketResponses(Ticket $ticket): \Illuminate\Database\Eloquent\Collection
    {
        return $ticket->responses()
            ->with(['user', 'adminUser'])
            ->orderBy('created_at', 'asc')
            ->get()
            ->map(function ($response) {
                return [
                    'id' => $response->id,
                    'message' => $response->message,
                    'created_at' => $response->created_at,
                    'is_customer' => $response->type === 'customer',
                    'author_name' => $response->user ? $response->user->name : ($response->adminUser ? $response->adminUser->name : 'System'),
                ];
            });
    }

    /**
     * Add a customer response to a ticket.
     *
     * @param Ticket $ticket
     * @param User $user
     * @param string $message
     * @return TicketResponse
     * @throws \InvalidArgumentException
     */
    public function addCustomerResponse(Ticket $ticket, User $user, string $message): TicketResponse
    {
        // Validate ticket can receive responses
        if ($ticket->status === Ticket::STATUS_CLOSED) {
            throw new \InvalidArgumentException('Cannot add responses to closed tickets.');
        }

        // Create response
        $response = TicketResponse::create([
            'ticket_id' => $ticket->id,
            'user_id' => $user->id,
            'type' => 'customer',
            'message' => trim($message),
            'is_internal' => false,
        ]);

        // Update ticket status if it was resolved
        if ($ticket->status === Ticket::STATUS_RESOLVED) {
            $ticket->update(['status' => Ticket::STATUS_IN_PROGRESS]);
        }

        // Log response addition
        $this->logCustomerResponseAdded($ticket, $user, 'customer');

        return $response->load(['user', 'adminUser']);
    }

    /**
     * Change ticket status with validation and logging.
     */
    public function changeStatus(Ticket $ticket, string $newStatus, string $notes = null): bool
    {
        // Validate status transition
        if (!$this->isValidStatusTransition($ticket->status, $newStatus)) {
            throw new \InvalidArgumentException("Invalid status transition from {$ticket->status} to {$newStatus}");
        }

        $oldStatus = $ticket->status;

        // Prepare update data
        $updateData = ['status' => $newStatus];

        // Add notes to internal notes if provided
        if ($notes) {
            $updateData['internal_notes'] = $this->appendToInternalNotes(
                $ticket->internal_notes,
                $newStatus,
                $notes
            );
        }

        // Update the ticket
        $ticket->update($updateData);

        // Fire event
        event(new TicketStatusChanged($ticket, $oldStatus, $newStatus));

        // Log the change
        $this->logStatusChange($ticket, $oldStatus, $newStatus, $notes);

        return true;
    }

    /**
     * Reassign ticket to different staff member or department.
     */
    public function reassignTicket(Ticket $ticket, int $assignedToId = null, int $departmentId = null): bool
    {
        $updateData = [];

        if ($assignedToId) {
            $updateData['assigned_to'] = $assignedToId;

            // If assigning to someone, set status to in progress if it's open
            if ($ticket->status === Ticket::STATUS_OPEN) {
                $updateData['status'] = Ticket::STATUS_IN_PROGRESS;
            }
        }

        if ($departmentId) {
            $updateData['department_id'] = $departmentId;
        }

        if (empty($updateData)) {
            return false;
        }

        $ticket->update($updateData);

        // Log the reassignment
        $this->logReassignment($ticket, $assignedToId, $departmentId);

        return true;
    }

    /**
     * Assign ticket to current user.
     */
    public function assignToSelf(Ticket $ticket, int $userId): bool
    {
        // Find admin user for the current user
        $adminUser = AdminUser::whereHas('user', function ($query) use ($userId) {
            $query->where('id', $userId);
        })->first();

        if (!$adminUser) {
            throw new \InvalidArgumentException('User is not an admin user');
        }

        return $this->reassignTicket($ticket, $adminUser->id);
    }

    /**
     * Add a response to a ticket.
     */
    public function addResponse(Ticket $ticket, array $responseData): TicketResponse
    {
        $response = TicketResponse::create([
            'ticket_id' => $ticket->id,
            'admin_user_id' => $responseData['admin_user_id'] ?? null,
            'user_id' => $responseData['user_id'] ?? null,
            'type' => $responseData['is_internal'] ? TicketResponse::TYPE_INTERNAL : TicketResponse::TYPE_STAFF,
            'message' => $responseData['message'],
            'is_internal' => $responseData['is_internal'] ?? false,
            'response_time_minutes' => $this->calculateResponseTime($ticket),
        ]);

        // Update ticket's last response time
        $ticket->update(['updated_at' => now()]);

        // Log the response
        $this->logResponseAdded($ticket, $response);

        return $response;
    }

    /**
     * Escalate a ticket to higher priority or different department.
     */
    public function escalateTicket(Ticket $ticket, string $reason = null): bool
    {
        // Increase priority if possible
        $newPriority = $this->getEscalatedPriority($ticket->priority);

        $updateData = ['priority' => $newPriority];

        // Add escalation note
        if ($reason) {
            $updateData['internal_notes'] = $this->appendToInternalNotes(
                $ticket->internal_notes,
                'escalated',
                "Escalated: {$reason}"
            );
        }

        $ticket->update($updateData);

        // Log the escalation
        $this->logEscalation($ticket, $reason);

        return true;
    }

    /**
     * Append text to internal notes with timestamp and user info.
     */
    protected function appendToInternalNotes(string $existingNotes = null, string $action, string $notes): string
    {
        $timestamp = now()->format('Y-m-d H:i:s');
        $user = auth()->user();
        $userName = $user->name ?? 'System';

        $newNote = "[{$timestamp}] {$userName}: " . ucfirst(str_replace('_', ' ', $action));
        if ($notes) {
            $newNote .= " - {$notes}";
        }

        return $existingNotes ? $existingNotes . "\n\n" . $newNote : $newNote;
    }

    /**
     * Calculate response time in minutes.
     */
    protected function calculateResponseTime(Ticket $ticket): int
    {
        return $ticket->created_at->diffInMinutes(now());
    }

    /**
     * Get escalated priority level.
     */
    protected function getEscalatedPriority(string $currentPriority): string
    {
        return match($currentPriority) {
            'low' => 'medium',
            'medium' => 'high',
            'high' => 'urgent',
            'urgent' => 'urgent', // Already at highest
            default => 'medium',
        };
    }

    /**
     * Log status change.
     */
    protected function logStatusChange(Ticket $ticket, string $oldStatus, string $newStatus, string $notes = null): void
    {
        Log::info('Ticket status changed', [
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'old_status' => $oldStatus,
            'new_status' => $newStatus,
            'notes' => $notes,
            'user_id' => auth()->id(),
        ]);
    }

    /**
     * Log ticket reassignment.
     */
    protected function logReassignment(Ticket $ticket, int $assignedToId = null, int $departmentId = null): void
    {
        Log::info('Ticket reassigned', [
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'assigned_to' => $assignedToId,
            'department_id' => $departmentId,
            'user_id' => auth()->id(),
        ]);
    }

    /**
     * Log response addition.
     */
    protected function logResponseAdded(Ticket $ticket, TicketResponse $response): void
    {
        Log::info('Ticket response added', [
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'response_id' => $response->id,
            'is_internal' => $response->is_internal,
            'user_id' => auth()->id(),
        ]);
    }

    /**
     * Log ticket escalation.
     */
    protected function logEscalation(Ticket $ticket, string $reason = null): void
    {
        Log::info('Ticket escalated', [
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'new_priority' => $ticket->priority,
            'reason' => $reason,
            'user_id' => auth()->id(),
        ]);
    }

    /**
     * Calculate SLA due date based on priority.
     */
    public function calculateSLADueDate(string $priority): \Carbon\Carbon
    {
        $slaHours = [
            Ticket::PRIORITY_URGENT => 2,   // 2 hours
            Ticket::PRIORITY_HIGH => 8,     // 8 hours
            Ticket::PRIORITY_NORMAL => 24,  // 24 hours
            Ticket::PRIORITY_LOW => 72,     // 72 hours
        ];

        $hours = $slaHours[$priority] ?? 24;
        return now()->addHours($hours);
    }

    /**
     * Get default department for ticket category.
     */
    public function getDefaultDepartmentForCategory(string $category): ?int
    {
        $departmentMapping = [
            Ticket::CATEGORY_BILLING => 'Revenue Operations',
            Ticket::CATEGORY_TECHNICAL => 'Information Technology',
            Ticket::CATEGORY_SALES => 'Business Development',
            Ticket::CATEGORY_GENERAL => 'Customer Experience',
        ];

        $departmentName = $departmentMapping[$category] ?? 'Customer Experience';

        $department = \App\Models\Department::where('name', $departmentName)->first();
        return $department ? $department->id : null;
    }

    /**
     * Normalize and validate ticket data from request.
     *
     * @param array $data
     * @return array
     * @throws \InvalidArgumentException
     */
    private function normalizeTicketData(array $data): array
    {
        // Handle both 'category' (direct) and 'department' (from Nova tool) fields
        $category = $data['category'] ?? $data['department'] ?? 'general';

        // Map priority values (Nova tool uses 'medium', database uses 'normal')
        $priority = $data['priority'] ?? 'normal';
        if ($priority === 'medium') {
            $priority = 'normal';
        }

        // Validate category
        if (!in_array($category, array_keys(Ticket::getCategories()))) {
            throw new \InvalidArgumentException("Invalid category: {$category}");
        }

        // Validate priority
        if (!in_array($priority, array_keys(Ticket::getPriorities()))) {
            throw new \InvalidArgumentException("Invalid priority: {$priority}");
        }

        return [
            'subject' => trim($data['subject']),
            'description' => trim($data['description']),
            'category' => $category,
            'priority' => $priority,
        ];
    }



    /**
     * Create initial customer response for a ticket.
     *
     * @param Ticket $ticket
     * @param User $user
     * @param string $description
     * @return TicketResponse
     */
    private function createInitialResponse(Ticket $ticket, User $user, string $description): TicketResponse
    {
        return TicketResponse::create([
            'ticket_id' => $ticket->id,
            'user_id' => $user->id,
            'type' => 'customer',
            'message' => $description,
            'is_internal' => false,
        ]);
    }

    /**
     * Build query for customer tickets with filters.
     *
     * @param Customer $customer
     * @param array $filters
     * @return \Illuminate\Database\Eloquent\Relations\HasMany|\Illuminate\Database\Eloquent\Builder
     */
    private function buildCustomerTicketsQuery(Customer $customer, array $filters)
    {
        $query = $customer->tickets()
            ->with(['responses.user', 'responses.adminUser', 'assignedTo', 'department'])
            ->orderBy('created_at', 'desc');

        // Apply search filter
        if (!empty($filters['search'])) {
            $searchTerm = $filters['search'];
            $query->where(function ($q) use ($searchTerm) {
                $q->where('ticket_number', 'like', "%{$searchTerm}%")
                  ->orWhere('subject', 'like', "%{$searchTerm}%")
                  ->orWhere('description', 'like', "%{$searchTerm}%");
            });
        }

        // Apply status filter
        if (!empty($filters['status'])) {
            $query->where('status', $filters['status']);
        }

        // Apply category filter
        if (!empty($filters['category'])) {
            $query->where('category', $filters['category']);
        }

        // Apply priority filter
        if (!empty($filters['priority'])) {
            $query->where('priority', $filters['priority']);
        }

        return $query;
    }

    /**
     * Log ticket creation for audit trail.
     *
     * @param Ticket $ticket
     * @param Customer $customer
     * @param User $user
     * @return void
     */
    private function logTicketCreation(Ticket $ticket, Customer $customer, User $user): void
    {
        Log::info('Customer Ticket Created', [
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'customer_id' => $customer->id,
            'customer_name' => $customer->full_name,
            'user_id' => $user->id,
            'user_email' => $user->email,
            'subject' => $ticket->subject,
            'category' => $ticket->category,
            'priority' => $ticket->priority,
            'source' => $ticket->source,
        ]);
    }

    /**
     * Log customer response addition for audit trail.
     *
     * @param Ticket $ticket
     * @param User $user
     * @param string $type
     * @return void
     */
    private function logCustomerResponseAdded(Ticket $ticket, User $user, string $type): void
    {
        Log::info('Ticket Response Added', [
            'ticket_id' => $ticket->id,
            'ticket_number' => $ticket->ticket_number,
            'user_id' => $user->id,
            'user_email' => $user->email,
            'response_type' => $type,
        ]);
    }

    /**
     * Check if status transition is valid.
     */
    public function isValidStatusTransition(string $fromStatus, string $toStatus): bool
    {
        $validTransitions = [
            Ticket::STATUS_OPEN => [Ticket::STATUS_IN_PROGRESS, Ticket::STATUS_RESOLVED, Ticket::STATUS_CLOSED],
            Ticket::STATUS_IN_PROGRESS => [Ticket::STATUS_OPEN, Ticket::STATUS_RESOLVED, Ticket::STATUS_CLOSED],
            Ticket::STATUS_RESOLVED => [Ticket::STATUS_IN_PROGRESS, Ticket::STATUS_CLOSED],
            Ticket::STATUS_CLOSED => [Ticket::STATUS_IN_PROGRESS], // Can reopen if needed
        ];

        return in_array($toStatus, $validTransitions[$fromStatus] ?? []);
    }
}
